### ISSUE TITLE
在 locales 配置不存在 en-US 时报错了

### ISSUE THREAD

**Issue by awmleer** [xiaohuoni/umi-plugin-mobile-dumi#2]
https://github.com/xiaohuoni/umi-plugin-mobile-dumi/blob/e30e94d81178ac5929d10c41f5a1ac3b91c16bfa/src/getDisplayContent.ts#L8

这里不能写死的去取 `en-US`，有些项目是没有 en-US 这个 locale 的

![image](https://user-images.githubusercontent.com/16526078/134477595-ea04acb6-77bf-4ba9-961f-e853b192645e.png)

**Comment by xiaohuoni** [comment]
这个只是给 mobile@5 使用的。
@PeachScript 有更优雅的取法吗？

**Comment by PeachScript** [comment]
试试：
```tsx
import { context } from 'dumi/theme';

const { config: { title } } = useContext(context);
```

**Comment by xiaohuoni** [comment]
上面的方法没取到，我直接取了 config 里面的 title 配置。
https://github.com/xiaohuoni/umi-plugin-mobile-dumi/commit/de9e870b72402e12974bc94214d0a1c543f1017b
